# Generated by Django 3.2.4 on 2022-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('discount', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('kurta', 'kurta'), ('jeans', 'jeans')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('colour', models.CharField(max_length=15)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
