# Generated by Django 4.0.4 on 2022-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('discount_price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL')], max_length=120)),
                ('color', models.CharField(max_length=15)),
                ('slug', models.SlugField(default='', max_length=225)),
            ],
        ),
    ]
