# Generated by Django 4.0.4 on 2022-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published',
        ),
    ]
