# Generated by Django 3.2.19 on 2023-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('L', 'Lamp'), ('CL', 'Ceiling Light'), ('WL', 'Wall Light'), ('RM', 'Room Light'), ('OT', 'Outdoor Light')], max_length=2),
        ),
    ]
